import Head from 'next/head'
import styled from 'styled-components'
//components
import Sidebar from '../components/sidebar/Sidebar'
import Welcome from '../components/welcome/Welcome'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Signal Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Container>
        <Sidebar />
        <Welcome />
      </Container>
    </div>
  )
}

const Container = styled.div`
  display: flex;
`
